"""Public API for reproducible Geometric Function Atlas computations."""

from .artifacts import (
    SNAPSHOT_SCHEMA_VERSION,
    class_info,
    coefficient_bound,
    expansion,
    get_proof,
    list_proofs,
    open_problems,
    reconciliation,
    references,
    snapshot_info,
    snapshot_payload,
    snapshot_verify,
    validate_snapshot_payload,
    verify_certificate,
)
from .artifacts import (
    list_classes as list_artifact_classes,
)
from .catalog import get_generator, list_generators
from .citation import CitationBundle, citation_export, citation_formats, format_citation
from .classes import (
    ClassAdmissibilityResult,
    ClassContainmentResult,
    ClassMembershipResult,
    class_admissibility,
    class_containment_screen,
    class_extremal_coefficients,
    class_member_screen,
    list_classes,
)
from .coefficients import GeneratorSeriesResult, generator_series, taylor_coefficients
from .contracts import (  # noqa: F401
    RESULT_SCHEMA_VERSION,
    CheckStatus,
    CorruptArtifactError,
    FailureState,
    InvalidInputError,
    LiteratureStatus,
    ResourceLimitError,
    UnresolvedError,
    UnsupportedError,
    VerificationCheck,
    VerificationReport,
    failure_payload,
    load_error_schema,
    load_result_schema,
    validate_error_payload,
    validate_result_payload,
)
from .counterexamples import (
    CounterexampleResult,
    WitnessSearchResult,
    find_counterexample,
    verify_counterexample,
)
from .exact import ExactExpressionError, parse_exact_expression
from .fekete_szego import FeketeSzegoResult, fekete_szego
from .implementation_registry import (  # noqa: F401
    get_trusted_implementation,
    list_trusted_implementations,
)
from .models import Generator
from .models import Z as z
from .plotting import (
    ConformalGrid,
    DomainPlotResult,
    PlotResult,
    conformal_grid,
    generator_function_coefficients,
    write_coefficient_plot,
    write_domain_plot,
    write_phase_plot,
    write_plot,
    write_real_part_plot,
)
from .radii import (
    RadiusCertificate,
    RadiusProvenance,
    RadiusRecord,
    RadiusReplayResult,
    RadiusStatus,
    audit_radius,
    identify_radius,
    list_radii,
    radius,
    recompute_radius,
    replay_radius_certificate,
    verify_radius_attainment,
    verify_radius_certificate,
)
from .records import RecordError, build_screen_record, validate_screen_record
from .snapshot import (
    Application,
    Counterexample,
    Evidence,
    Fact,
    FamilyDetail,
    FunctionFamily,
    FunctionInstance,
    LegacyFunction,
    Paper,
    PaperClaim,
    PaperDetail,
    PropertyImplication,
    RegistrySnapshot,
    SearchResult,
    SnapshotError,
    SnapshotInfo,
    SnapshotIntegrityError,
    SnapshotManifest,
    SnapshotManifestError,
    SnapshotResourceLimitError,
    SnapshotStats,
    SnapshotVerification,
    Tag,
    VerificationRun,
    install_snapshot,
)
from .snapshot import (
    snapshot_info as registry_snapshot_info,
)
from .snapshot import (
    verify_snapshot as verify_registry_snapshot,
)
from .verify import FunctionVerificationResult, verify_function
from .version import __version__

list_screen_classes = list_classes
verify_snapshot = verify_registry_snapshot

__all__ = [
    "SNAPSHOT_SCHEMA_VERSION",
    "Application",
    "CitationBundle",
    "ClassAdmissibilityResult",
    "ClassContainmentResult",
    "ClassMembershipResult",
    "ConformalGrid",
    "Counterexample",
    "CounterexampleResult",
    "DomainPlotResult",
    "Evidence",
    "ExactExpressionError",
    "Fact",
    "FamilyDetail",
    "FeketeSzegoResult",
    "FunctionFamily",
    "FunctionInstance",
    "FunctionVerificationResult",
    "Generator",
    "GeneratorSeriesResult",
    "LegacyFunction",
    "Paper",
    "PaperClaim",
    "PaperDetail",
    "PlotResult",
    "PropertyImplication",
    "RadiusCertificate",
    "RadiusProvenance",
    "RadiusRecord",
    "RadiusReplayResult",
    "RadiusStatus",
    "RecordError",
    "RegistrySnapshot",
    "SearchResult",
    "SnapshotError",
    "SnapshotInfo",
    "SnapshotIntegrityError",
    "SnapshotManifest",
    "SnapshotManifestError",
    "SnapshotResourceLimitError",
    "SnapshotStats",
    "SnapshotVerification",
    "Tag",
    "VerificationRun",
    "WitnessSearchResult",
    "__version__",
    "audit_radius",
    "build_screen_record",
    "citation_export",
    "citation_formats",
    "class_admissibility",
    "class_containment_screen",
    "class_extremal_coefficients",
    "class_info",
    "class_member_screen",
    "coefficient_bound",
    "conformal_grid",
    "expansion",
    "fekete_szego",
    "find_counterexample",
    "format_citation",
    "generator_function_coefficients",
    "generator_series",
    "get_generator",
    "get_proof",
    "identify_radius",
    "install_snapshot",
    "list_artifact_classes",
    "list_classes",
    "list_generators",
    "list_proofs",
    "list_radii",
    "list_screen_classes",
    "open_problems",
    "parse_exact_expression",
    "radius",
    "recompute_radius",
    "reconciliation",
    "references",
    "registry_snapshot_info",
    "replay_radius_certificate",
    "snapshot_info",
    "snapshot_payload",
    "snapshot_verify",
    "taylor_coefficients",
    "validate_screen_record",
    "validate_snapshot_payload",
    "verify_certificate",
    "verify_counterexample",
    "verify_function",
    "verify_radius_attainment",
    "verify_radius_certificate",
    "verify_snapshot",
    "write_coefficient_plot",
    "write_domain_plot",
    "write_phase_plot",
    "write_plot",
    "write_real_part_plot",
    "z",
]
