"""Public API for reproducible Geometric Function Atlas computations."""

from .catalog import get_generator, list_generators
from .classes import (
    ClassAdmissibilityResult,
    ClassContainmentResult,
    ClassMembershipResult,
    class_admissibility,
    class_containment_screen,
    class_extremal_coefficients,
    class_member_screen,
    list_classes,
)
from .coefficients import GeneratorSeriesResult, generator_series, taylor_coefficients
from .contracts import (  # noqa: F401
    RESULT_SCHEMA_VERSION,
    CheckStatus,
    CorruptArtifactError,
    FailureState,
    InvalidInputError,
    LiteratureStatus,
    ResourceLimitError,
    UnresolvedError,
    UnsupportedError,
    VerificationCheck,
    VerificationReport,
    failure_payload,
    load_error_schema,
    load_result_schema,
    validate_error_payload,
    validate_result_payload,
)
from .counterexamples import (
    CounterexampleResult,
    WitnessSearchResult,
    find_counterexample,
    verify_counterexample,
)
from .fekete_szego import FeketeSzegoResult, fekete_szego
from .implementation_registry import (  # noqa: F401
    get_trusted_implementation,
    list_trusted_implementations,
)
from .models import Generator
from .models import Z as z
from .plotting import (
    ConformalGrid,
    DomainPlotResult,
    PlotResult,
    conformal_grid,
    generator_function_coefficients,
    write_coefficient_plot,
    write_domain_plot,
    write_phase_plot,
    write_plot,
    write_real_part_plot,
)
from .records import RecordError, build_screen_record, validate_screen_record
from .snapshot import (
    Application,
    Counterexample,
    Evidence,
    Fact,
    FamilyDetail,
    FunctionFamily,
    FunctionInstance,
    Paper,
    PaperClaim,
    PaperDetail,
    PropertyImplication,
    RegistrySnapshot,
    SearchResult,
    SnapshotError,
    SnapshotInfo,
    SnapshotIntegrityError,
    SnapshotManifest,
    SnapshotManifestError,
    SnapshotResourceLimitError,
    SnapshotStats,
    SnapshotVerification,
    VerificationRun,
    install_snapshot,
    snapshot_info,
    verify_snapshot,
)
from .verify import FunctionVerificationResult, verify_function
from .version import __version__

__all__ = [
    "Application",
    "ClassAdmissibilityResult",
    "ClassContainmentResult",
    "ClassMembershipResult",
    "ConformalGrid",
    "Counterexample",
    "CounterexampleResult",
    "DomainPlotResult",
    "Evidence",
    "Fact",
    "FeketeSzegoResult",
    "FamilyDetail",
    "FunctionFamily",
    "FunctionInstance",
    "FunctionVerificationResult",
    "Generator",
    "GeneratorSeriesResult",
    "PlotResult",
    "Paper",
    "PaperClaim",
    "PaperDetail",
    "PropertyImplication",
    "RegistrySnapshot",
    "RecordError",
    "SearchResult",
    "SnapshotError",
    "SnapshotInfo",
    "SnapshotIntegrityError",
    "SnapshotManifest",
    "SnapshotManifestError",
    "SnapshotResourceLimitError",
    "SnapshotStats",
    "SnapshotVerification",
    "VerificationRun",
    "WitnessSearchResult",
    "__version__",
    "build_screen_record",
    "class_admissibility",
    "class_containment_screen",
    "class_extremal_coefficients",
    "class_member_screen",
    "conformal_grid",
    "fekete_szego",
    "find_counterexample",
    "generator_function_coefficients",
    "generator_series",
    "get_generator",
    "install_snapshot",
    "list_classes",
    "list_generators",
    "snapshot_info",
    "taylor_coefficients",
    "validate_screen_record",
    "verify_counterexample",
    "verify_snapshot",
    "verify_function",
    "write_coefficient_plot",
    "write_domain_plot",
    "write_phase_plot",
    "write_plot",
    "write_real_part_plot",
    "z",
]
