"""Versioned baked scientific artifacts and bounded certificate replay.

The Geometric Function Atlas website publishes immutable scientific artifacts:
Schur-parameter coefficient expansions, a coefficient-bound catalog, machine
proof certificates, open-problem brackets and conjectures, literature
reconciliation rows, and a method reference document. This module exposes those
artifacts through the standalone package as a versioned, checksummed, read-only
snapshot (``src/geometric_function_atlas/data/``), regenerated by
``scripts/bake_artifacts.py`` from the website repository.

Evidence boundaries (the website's honesty model, preserved here):

* Exact expansion and bound strings are exact *transcriptions* of the published
  snapshot; sharpness, enclosure, attainment, and provenance are carried by the
  record fields and are never inferred by this package.
* ``verify_certificate`` replays the certificate's declared extremal through the
  package's exact Schur machinery. A passing replay certifies that the stored
  extremal attains the stored candidate under the declared class assumptions; it
  is not a new proof and not peer review.
* Every lookup is fail-closed: unknown keys, missing artifacts, checksum or
  schema mismatches, unsupported functionals, and resource exhaustion raise
  explicit errors; nothing is guessed.

All payloads are deterministic JSON under the closed ``snapshot`` result
envelope documented in ``docs/RESULT_CONTRACT.md``.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping
from functools import cache
from importlib import resources
from typing import Any

import sympy as sp

from .contracts import (
    CheckStatus,
    CorruptArtifactError,
    InvalidInputError,
    LiteratureStatus,
    UnresolvedError,
    UnsupportedError,
    VerificationCheck,
    VerificationReport,
)
from .exact import ExactExpressionError, parse_exact_expression
from .models import canonical_expression_dag
from .schur import functional_value, member_coefficients
from .version import __version__

SNAPSHOT_SCHEMA_VERSION = 1
MAX_SNAPSHOT_JSON_NODES = 10_000
MAX_REPLAY_ORDER = 3  # hankel2_2 / Zalcman need a2..a4 at most

_SNAPSHOT_RESULT_TYPES = frozenset(
    {
        "certificate_replay",
        "classes",
        "coefficient_bound",
        "expansion",
        "open_problems",
        "proof",
        "proofs",
        "reconciliation",
        "references",
        "snapshot_verify",
    }
)

_LOOKUP_METHODS = {
    "certificate_replay": "exact_schur_extremal_replay",
    "classes": "baked_class_catalog_lookup",
    "coefficient_bound": "baked_coefficient_bound_lookup",
    "expansion": "baked_expansion_lookup",
    "open_problems": "baked_open_problems_query",
    "proof": "baked_proof_detail_lookup",
    "proofs": "baked_proof_gallery_query",
    "reconciliation": "baked_reconciliation_query",
    "references": "baked_references_document",
    "snapshot_verify": "baked_snapshot_integrity_verification",
}

_REPLAY_EVIDENCE = "proven_exact_under_declared_assumptions"
_LOOKUP_EVIDENCE = "screened"

_GAMMA_STRING = re.compile(r"^[+-]?[0-9]+(?:/[0-9]+)?$", re.ASCII)


def _data_file(name: str) -> Any:
    """Return the packaged resource handle for one baked artifact."""
    return resources.files("geometric_function_atlas").joinpath("data", name)


@cache
def _load_json(name: str) -> dict[str, Any]:
    """Load one baked JSON artifact, failing closed on absence or corruption."""
    try:
        text = _data_file(name).read_text(encoding="utf-8")
    except (FileNotFoundError, IsADirectoryError, OSError) as exc:
        raise CorruptArtifactError(
            f"baked artifact {name} is missing from the package data"
        ) from exc
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise CorruptArtifactError(f"baked artifact {name} is not valid JSON") from exc
    if not isinstance(payload, dict):
        raise CorruptArtifactError(f"baked artifact {name} is not a JSON object")
    return payload


@cache
def _load_text(name: str) -> str:
    try:
        return _data_file(name).read_text(encoding="utf-8")
    except (FileNotFoundError, IsADirectoryError, OSError) as exc:
        raise CorruptArtifactError(
            f"baked artifact {name} is missing from the package data"
        ) from exc


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _check_schema(payload: Mapping[str, Any], name: str) -> None:
    version = payload.get("schema_version")
    if not isinstance(version, int) or isinstance(version, bool):
        raise CorruptArtifactError(
            f"baked artifact {name} carries no integer schema_version"
        )
    if version != SNAPSHOT_SCHEMA_VERSION:
        raise CorruptArtifactError(
            f"baked artifact {name} uses schema_version {version}, "
            f"expected {SNAPSHOT_SCHEMA_VERSION}"
        )


def _manifest() -> dict[str, Any]:
    manifest = _load_json("manifest.json")
    _check_schema(manifest, "manifest.json")
    return manifest


def _classes_payload() -> dict[str, Any]:
    payload = _load_json("classes.json")
    _check_schema(payload, "classes.json")
    return payload["classes"]


def _require_class(class_key: str) -> dict[str, Any]:
    classes = _classes_payload()
    try:
        return classes[class_key]
    except KeyError as exc:
        available = ", ".join(sorted(classes))
        raise UnsupportedError(
            f"unknown class {class_key!r}; available classes: {available}"
        ) from exc


def _normalize_gamma(value: Any) -> Any:
    """Return a replay-safe exact Schur parameter from a certificate record.

    The baked certificates store integer strings (``"0"``), integer values, and
    exactly-representable float zeros/ones (``0.0``, ``1.0``). Floats that are
    not exactly integer-valued cannot be replayed exactly and fail closed.
    """
    if isinstance(value, bool):
        raise UnresolvedError("certificate extremal gamma is a bool")
    if isinstance(value, float):
        if value.is_integer():
            return int(value)
        raise UnresolvedError(
            f"certificate extremal gamma {value!r} is not exactly representable"
        )
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        if _GAMMA_STRING.fullmatch(value) is None:
            raise UnresolvedError(
                f"certificate extremal gamma {value!r} is not an exact rational"
            )
        return value
    raise UnresolvedError(
        f"certificate extremal gamma has unsupported type {type(value).__name__}"
    )


def _exact_or_float(record: Mapping[str, Any], key: str) -> sp.Expr | float | None:
    """Parse an exact string field, falling back to its float sibling."""
    value = record.get(key)
    if isinstance(value, str):
        try:
            return parse_exact_expression(value)
        except ExactExpressionError:
            pass
    sibling = record.get(f"{key}_float")
    if isinstance(sibling, (int, float)):
        return float(sibling)
    return None


# ── snapshot integrity ────────────────────────────────────────────────────────


def snapshot_info() -> dict[str, Any]:
    """Return the snapshot identity record (version, date, source, files)."""
    manifest = _manifest()
    files = dict(sorted(manifest["files"].items()))
    return {
        "artifact_version": manifest["artifact_version"],
        "snapshot_date": manifest["snapshot_date"],
        "source_repo": manifest["source_repo"],
        "source_commit": manifest["source_commit"],
        "schema_version": manifest["schema_version"],
        "recipe": manifest["recipe"],
        "files": {
            name: {
                "sha256": entry["sha256"],
                "schema_version": entry.get("schema_version"),
            }
            for name, entry in files.items()
        },
    }


def snapshot_verify() -> dict[str, Any]:
    """Verify every baked artifact against the shipped manifest checksums.

    Any missing file, checksum mismatch, or schema-version mismatch raises
    :class:`CorruptArtifactError`; a passing call returns the integrity record.
    """
    manifest = _manifest()
    checks: list[VerificationCheck] = []
    for name in sorted(manifest["files"]):
        entry = manifest["files"][name]
        resource = _data_file(name)
        try:
            observed = _sha256_bytes(resource.read_bytes())
        except (FileNotFoundError, IsADirectoryError, OSError) as exc:
            raise CorruptArtifactError(
                f"baked artifact {name} is missing from the package data"
            ) from exc
        ok = observed == entry["sha256"]
        checks.append(
            VerificationCheck(
                name=f"artifact_checksum_{name}",
                checked=f"SHA-256 of data/{name}",
                expected=entry["sha256"],
                observed=observed,
                status=CheckStatus.PASS if ok else CheckStatus.FAIL,
                scope="shipped snapshot integrity",
                failure_reason=None if ok else "checksum mismatch",
            )
        )
        if ok and name.endswith(".json"):
            payload = json.loads(resource.read_text(encoding="utf-8"))
            version = payload.get("schema_version")
            schema_ok = isinstance(version, int) and not isinstance(version, bool) and (
                version == SNAPSHOT_SCHEMA_VERSION
            )
            checks.append(
                VerificationCheck(
                    name=f"artifact_schema_{name}",
                    checked=f"schema_version of data/{name}",
                    expected=SNAPSHOT_SCHEMA_VERSION,
                    observed=version,
                    status=CheckStatus.PASS if schema_ok else CheckStatus.FAIL,
                    scope="shipped snapshot integrity",
                    failure_reason=None if schema_ok else "schema version mismatch",
                )
            )
    report = VerificationReport(tuple(checks))
    if not report.success:
        failed = [check for check in checks if check.status is CheckStatus.FAIL]
        detail = "; ".join(f"{check.name}: {check.failure_reason}" for check in failed)
        raise CorruptArtifactError(f"snapshot verification failed: {detail}")
    return {
        "artifact_version": manifest["artifact_version"],
        "snapshot_date": manifest["snapshot_date"],
        "source_commit": manifest["source_commit"],
        "files_verified": len(manifest["files"]),
        "checks": report.to_dict(),
    }


# ── class catalog ─────────────────────────────────────────────────────────────


def list_classes() -> list[dict[str, Any]]:
    """Return the 39-class Ma–Minda catalog with exact phi coefficients."""
    return [
        {
            "key": key,
            "name": record["name"],
            "phi_formula": record["phi_formula"],
            "citation": record["citation"],
            "phi_coeffs": list(record["phi_coeffs"]),
        }
        for key, record in sorted(_classes_payload().items())
    ]


def class_info(class_key: str) -> dict[str, Any]:
    """Return one class record; unknown classes fail closed as unsupported."""
    record = _require_class(class_key)
    return {
        "key": class_key,
        "name": record["name"],
        "phi_formula": record["phi_formula"],
        "citation": record["citation"],
        "phi_coeffs": list(record["phi_coeffs"]),
    }


# ── expansions ────────────────────────────────────────────────────────────────


def expansion(class_key: str) -> dict[str, Any]:
    """Look up the website's Schur-parameter coefficient expansion for a class."""
    _require_class(class_key)
    payload = _load_json("expansions.json")
    _check_schema(payload, "expansions.json")
    try:
        record = payload["classes"][class_key]
    except KeyError as exc:
        available = ", ".join(sorted(payload["classes"]))
        raise UnsupportedError(
            f"class {class_key!r} has no baked expansion; available: {available}"
        ) from exc
    return {
        "class_key": class_key,
        "phi_latex": record["phi_latex"],
        "phi_coeffs_latex": list(record["phi_coeffs_latex"]),
        "coeffs": [dict(entry) for entry in record["coeffs"]],
    }


# ── coefficient bounds ────────────────────────────────────────────────────────


def coefficient_bound(
    class_key: str, functional_key: str | None = None
) -> dict[str, Any]:
    """Look up the baked coefficient-bound catalog for one class.

    The published record preserves the sharp-versus-enclosure distinction in
    its ``sharp`` field: a sharp entry carries ``value_exact`` equal to the
    bound; an enclosure carries only the certified upper ``bound`` and slack.
    """
    _require_class(class_key)
    payload = _load_json("bounds.json")
    _check_schema(payload, "bounds.json")
    try:
        entries = payload["classes"][class_key]
    except KeyError as exc:
        available = ", ".join(sorted(payload["classes"]))
        raise UnsupportedError(
            f"class {class_key!r} has no baked bounds; available: {available}"
        ) from exc
    if functional_key is not None:
        try:
            record = entries[functional_key]
        except KeyError as exc:
            available = ", ".join(sorted(entries))
            raise UnsupportedError(
                f"class {class_key!r} has no bound for functional "
                f"{functional_key!r}; available: {available}"
            ) from exc
        return {
            "class_key": class_key,
            "functional_key": functional_key,
            "bound": record["bound"],
            "bound_float": record["bound_float"],
            "sharp": bool(record["sharp"]),
            "slack": record.get("slack"),
            "value_exact": record.get("value_exact"),
        }
    return {
        "class_key": class_key,
        "count": len(entries),
        "entries": {
            functional: {
                "bound": record["bound"],
                "bound_float": record["bound_float"],
                "sharp": bool(record["sharp"]),
                "slack": record.get("slack"),
                "value_exact": record.get("value_exact"),
            }
            for functional, record in sorted(entries.items())
        },
    }


# ── proofs gallery and detail ─────────────────────────────────────────────────


def _certificates() -> dict[str, dict[str, Any]]:
    payload = _load_json("certificates.json")
    _check_schema(payload, "certificates.json")
    return payload["certificates"]


def _proof_summary(name: str, record: Mapping[str, Any]) -> dict[str, Any]:
    sharp = record.get("sharp") or {}
    # ``sharp`` means proven sharpness. The certificate's ``exact`` flag only
    # says the candidate is an exact constant; without ``proven`` it remains a
    # certified upper enclosure. The two must stay distinct.
    return {
        "name": name,
        "class_key": record["class"],
        "functional_key": record["functional"],
        "status": record["status"],
        "bound": record.get("bound"),
        "sharp": bool(sharp.get("proven")),
        "statement": record.get("statement"),
    }


def list_proofs(
    class_key: str | None = None,
    functional_key: str | None = None,
    status: str | None = None,
    search: str | None = None,
) -> dict[str, Any]:
    """Return proof-gallery rows, optionally filtered.

    Unknown class or functional filters fail closed as unsupported; an empty
    match set is a valid result (the corpus simply has no such row).
    """
    certificates = _certificates()
    if class_key is not None:
        _require_class(class_key)
    if functional_key is not None:
        _functional_exists(functional_key)
    if status is not None:
        known = {record["status"] for record in certificates.values()}
        if status not in known:
            raise UnsupportedError(
                f"unknown proof status {status!r}; corpus statuses: {sorted(known)}"
            )
    rows = []
    for name, record in sorted(certificates.items()):
        if class_key is not None and record["class"] != class_key:
            continue
        if functional_key is not None and record["functional"] != functional_key:
            continue
        if status is not None and record["status"] != status:
            continue
        if search is not None:
            needle = search.lower()
            haystack = f"{name} {record.get('statement', '')}".lower()
            if needle not in haystack:
                continue
        rows.append(_proof_summary(name, record))
    return {"count": len(rows), "rows": rows}


def _functional_exists(functional_key: str) -> None:
    certificates = _certificates()
    known = {record["functional"] for record in certificates.values()}
    if functional_key not in known:
        raise UnsupportedError(
            f"unknown functional {functional_key!r}; corpus functionals: "
            f"{sorted(known)}"
        )


def get_proof(name: str, *, raw: bool = False) -> dict[str, Any]:
    """Return one proof certificate's detail record, or the raw record."""
    certificates = _certificates()
    try:
        record = certificates[name]
    except KeyError as exc:
        raise UnsupportedError(
            f"unknown proof {name!r}; use 'gfa proofs' to list certificate names"
        ) from exc
    from .schur import functional_display  # local import avoids a cycle at load

    sharp = record.get("sharp") or {}
    candidate = sharp.get("candidate") or {}
    class_record = _require_class(record["class"])
    display = functional_display(record["functional"])
    detail = {
        "name": name,
        "class_key": record["class"],
        "class_name": class_record["name"],
        "functional_key": record["functional"],
        "functional_display": display[0],
        "functional_latex": display[1],
        "status": record["status"],
        "statement": record.get("statement"),
        "bound": record.get("bound"),
        "slack": record.get("slack"),
        "engine": record.get("engine"),
        "evaluator": (record.get("evaluator") or {}).get("definition"),
        "method_label": f"{record.get('engine')} / "
        f"{(record.get('evaluator') or {}).get('type', 'unknown')}",
        "lemmas": list(record.get("lemmas") or []),
        "n_leaves": record.get("n_leaves"),
        "n_leaves_parts": record.get("n_leaves_parts"),
        "leaves_npz": record.get("leaves_npz"),
        "sharp": {
            "proven": bool(sharp.get("proven")),
            "exact": bool(sharp.get("exact")),
            "bracket_lo": sharp.get("bracket_lo"),
            "bracket_hi": sharp.get("bracket_hi"),
            "candidate_exact": candidate.get("value_exact"),
            "candidate_float": candidate.get("value_float"),
            "candidate_method": candidate.get("method"),
            "extremal_gammas": list(sharp.get("extremal_gammas") or []),
            "extremal_omega": sharp.get("extremal_omega"),
            "method": sharp.get("method"),
            "note": sharp.get("note"),
            "reference": sharp.get("reference"),
        },
    }
    if raw:
        detail["certificate"] = dict(record)
    return detail


# ── open problems ─────────────────────────────────────────────────────────────


def open_problems(kind: str = "all") -> dict[str, Any]:
    """Return open-problem rows, preserving the two published categories.

    ``enclosure`` rows are certified brackets awaiting sharp closure;
    ``numerical`` rows are uncertified numerical conjectures. The two are never
    merged, and neither is presented as a proved sharp value.
    """
    if kind not in {"all", "enclosure", "numerical"}:
        raise InvalidInputError(
            "kind must be one of: all, enclosure, numerical"
        )
    payload = _load_json("open_problems.json")
    _check_schema(payload, "open_problems.json")
    enclosures = [dict(row) for row in payload["enclosures"]]
    conjectures = [dict(row) for row in payload["conjectures"]]
    counts = {"enclosures": len(enclosures), "numerical": len(conjectures)}
    record: dict[str, Any] = {"counts": counts}
    if kind in {"all", "enclosure"}:
        record["enclosures"] = enclosures
    if kind in {"all", "numerical"}:
        record["conjectures"] = conjectures
    return record


# ── reconciliation rows ───────────────────────────────────────────────────────


def _category_tokens(category: str) -> set[str]:
    """Split a reconciliation bucket into its letters.

    Rows may carry compound buckets such as ``"A+C*"`` (a row that falls under
    both the A and C summaries); each token is a single A–D letter.
    """
    return {token.rstrip("*") for token in category.split("+")}


def reconciliation(
    class_key: str | None = None,
    functional_key: str | None = None,
    category: str | None = None,
) -> dict[str, Any]:
    """Return literature-reconciliation counts and rows.

    ``counts`` are the published A–D summary buckets; ``rows`` may carry
    compound buckets (for example ``"A+C*"``). ``category`` filters rows whose
    bucket includes the given letter. No-match rows are literature findings,
    never novelty certificates.
    """
    payload = _load_json("reconciliation.json")
    _check_schema(payload, "reconciliation.json")
    counts = dict(payload["counts"])
    rows = [dict(row) for row in payload["rows"]]
    if category is not None:
        normalized = category.upper()
        if normalized not in counts:
            raise InvalidInputError(
                f"unknown reconciliation category {category!r}; categories: "
                f"{sorted(counts)}"
            )
    if class_key is not None:
        _require_class(class_key)
    if functional_key is not None:
        _functional_exists(functional_key)
    filtered = [
        row
        for row in rows
        if (class_key is None or row["class_key"] == class_key)
        and (functional_key is None or row["functional_key"] == functional_key)
        and (
            category is None
            or category.upper() in _category_tokens(row["category"])
        )
    ]
    return {"counts": counts, "total": len(rows), "rows": filtered}


# ── references document ───────────────────────────────────────────────────────


def references() -> dict[str, Any]:
    """Return the versioned method-reference companion document."""
    return {"document": _load_text("references.md")}


# ── bounded certificate replay ────────────────────────────────────────────────


def verify_certificate(name: str) -> dict[str, Any]:
    """Replay one certificate's declared extremal through the exact Schur machinery.

    The replay recomputes the coefficient functional at the certificate's
    stored extremal Schur parameters using the class phi coefficients from the
    versioned snapshot, then compares the exact value with the certificate's
    declared candidate. Fail-closed outcomes:

    * unknown certificate or unsupported functional -> ``UnsupportedError``;
    * extremal not exactly representable or absent -> ``UnresolvedError``;
    * resource bounds (Schur depth / coefficient order) -> ``ResourceLimitError``;
    * recomputed value inconsistent with the declared candidate or upper bound
      -> ``CorruptArtifactError``.

    A passing replay certifies extremal attainment of the stored candidate
    under the declared class assumptions; it is not a new proof and not peer
    review, and it does not depend on the stripped leaf archive.
    """
    certificates = _certificates()
    try:
        certificate = certificates[name]
    except KeyError as exc:
        raise UnsupportedError(
            f"unknown certificate {name!r}; use 'gfa proofs' to list names"
        ) from exc
    class_key = certificate["class"]
    functional_key = certificate["functional"]
    class_record = _require_class(class_key)
    sharp = certificate.get("sharp") or {}
    candidate = sharp.get("candidate") or {}
    gammas = sharp.get("extremal_gammas") or []
    if not gammas:
        raise UnresolvedError(
            f"certificate {name} carries no extremal gammas for replay"
        )
    normalized = [_normalize_gamma(value) for value in gammas]
    phi_coeffs = list(class_record["phi_coeffs"])
    coefficients = member_coefficients(
        phi_coeffs, normalized, order=MAX_REPLAY_ORDER
    )
    value = functional_value(functional_key, coefficients)
    value_float = float(sp.N(value, 30))

    bound = _exact_or_float(certificate, "bound")
    if bound is None:
        raise CorruptArtifactError(
            f"certificate {name} carries no bound value for replay"
        )
    bound_float = float(sp.N(bound, 30)) if isinstance(bound, sp.Expr) else float(bound)
    slack = certificate.get("slack")
    tolerance = float(slack) if isinstance(slack, (int, float)) else 1e-9

    expected_exact = candidate.get("value_exact")
    expected_float = candidate.get("value_float")

    checks: list[VerificationCheck] = []
    if expected_exact is not None:
        try:
            parsed = parse_exact_expression(str(expected_exact))
        except ExactExpressionError as exc:
            raise CorruptArtifactError(
                f"certificate {name} candidate value_exact is not a valid "
                "exact expression"
            ) from exc
        attained = sp.simplify(value - parsed) == 0
        expected = str(expected_exact)
    elif expected_float is not None:
        attained = abs(value_float - float(expected_float)) <= tolerance
        expected = f"{expected_float} ± {tolerance}"
    else:
        raise UnresolvedError(
            f"certificate {name} declares no candidate value for replay"
        )
    checks.append(
        VerificationCheck(
            name="extremal_attainment",
            checked="functional value at the stored extremal Schur parameters",
            expected=expected,
            observed=str(value),
            status=CheckStatus.PASS if attained else CheckStatus.FAIL,
            scope="certificate replay (exact Schur machinery)",
            failure_reason=None if attained else "recomputed value differs",
        )
    )

    bound_consistent = value_float <= bound_float + tolerance
    checks.append(
        VerificationCheck(
            name="upper_bound_consistency",
            checked="replayed value lies within the certified upper bound + slack",
            expected=f"{bound_float} + {tolerance}",
            observed=value_float,
            status=CheckStatus.PASS if bound_consistent else CheckStatus.FAIL,
            scope="certificate replay (exact Schur machinery)",
            failure_reason=None
            if bound_consistent
            else "replayed value exceeds the declared bound",
        )
    )
    report = VerificationReport(tuple(checks))
    if not report.success:
        failed = [check for check in checks if check.status is CheckStatus.FAIL]
        detail = "; ".join(f"{check.name}: {check.failure_reason}" for check in failed)
        raise CorruptArtifactError(
            f"certificate {name} failed replay: {detail}"
        )
    return {
        "name": name,
        "class_key": class_key,
        "functional_key": functional_key,
        "functional_value_exact": str(value),
        "functional_value_float": value_float,
        "candidate_exact": expected_exact,
        "candidate_float": expected_float,
        "bound": certificate.get("bound"),
        "bound_float": bound_float,
        "slack": slack,
        "sharp": bool(sharp.get("proven")),
        "matched": True,
    }


# ── closed snapshot result envelope ───────────────────────────────────────────


def _count_dag(count: int) -> dict[str, Any]:
    """Minimal canonical DAG encoding an exact record count."""
    return canonical_expression_dag({"count": sp.Integer(count)})


def _parse_exact_expression_map(
    expressions: Mapping[str, Any],
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Split named values into (exact-expressions, sympy DAG sources).

    Strings are parsed with the restricted eval-free parser; values that do not
    parse are omitted from the DAG (the checksummed record stays authoritative).
    """
    exact: dict[str, Any] = {}
    dag_sources: dict[str, Any] = {}
    for name, value in expressions.items():
        if isinstance(value, (list, tuple)):
            parsed: list[sp.Expr] = []
            for item in value:
                try:
                    parsed.append(parse_exact_expression(str(item)))
                except ExactExpressionError:
                    parsed = []
                    break
            if parsed:
                exact[name] = [str(item) for item in value]
                dag_sources[name] = parsed
        else:
            try:
                expr = parse_exact_expression(str(value))
            except ExactExpressionError:
                continue
            exact[name] = str(value)
            dag_sources[name] = expr
    return exact, dag_sources


def snapshot_payload(
    *,
    result_type: str,
    canonical_inputs: Mapping[str, Any],
    record: Mapping[str, Any],
    evidence_status: str,
    assumptions: tuple[str, ...] | list[str],
    source_references: tuple[str, ...] | list[str],
    verification: VerificationReport,
    exact_expressions: Mapping[str, Any] | None = None,
    record_count: int | None = None,
) -> dict[str, Any]:
    """Assemble the closed snapshot result envelope for one operation."""
    if result_type not in _SNAPSHOT_RESULT_TYPES:
        raise ValueError(f"unsupported snapshot result_type: {result_type!r}")
    manifest = _manifest()
    if exact_expressions:
        exact, dag_sources = _parse_exact_expression_map(exact_expressions)
        if dag_sources:
            dag = canonical_expression_dag(dag_sources)
        elif record_count is not None:
            exact = {}
            dag = _count_dag(record_count)
        else:
            dag = canonical_expression_dag(
                {"count": sp.Integer(len(json.dumps(record, sort_keys=True)))}
            )
    else:
        exact = {}
        count = record_count
        if count is None:
            count = len(record) if isinstance(record, Mapping) else 0
        dag = _count_dag(count)
    payload: dict[str, Any] = {
        "schema_version": SNAPSHOT_SCHEMA_VERSION,
        "result_type": result_type,
        "canonical_inputs": dict(canonical_inputs),
        "exact_expressions": exact,
        "exact_expression_dag": dag,
        "method": _LOOKUP_METHODS[result_type],
        "evidence_status": evidence_status,
        "computational_status": evidence_status,
        "assumptions": list(assumptions),
        "source_references": list(source_references),
        "package_version": __version__,
        "artifact_versions": {
            "generator_catalog": f"gfa_classes:{manifest['artifact_version']}",
            "source_commit": manifest["source_commit"],
            "fixture_or_proof": f"gfa_artifacts:{manifest['artifact_version']}",
            "snapshot_date": manifest["snapshot_date"],
            "snapshot_schema": str(SNAPSHOT_SCHEMA_VERSION),
        },
        "literature_status": LiteratureStatus.NOT_ASSESSED.value,
        "novelty_claim": False,
        "failure_state": None,
        "verification": verification.to_dict(),
        "provenance": "built_in",
        "record": dict(record),
    }
    json.dumps(payload, allow_nan=False)
    validate_snapshot_payload(payload)
    return payload


def validate_snapshot_payload(payload: Mapping[str, Any]) -> None:
    """Validate a snapshot result against the closed envelope.

    This dependency-free validator mirrors ``validate_error_payload``: it
    rejects unknown top-level keys, requires the exact envelope, and enforces
    the fail-closed status coherence rules. The JSON schema shipped at
    ``schema/result.schema.json`` accepts the same payloads.
    """
    envelope = {
        "schema_version",
        "result_type",
        "canonical_inputs",
        "exact_expressions",
        "exact_expression_dag",
        "method",
        "evidence_status",
        "computational_status",
        "assumptions",
        "source_references",
        "package_version",
        "artifact_versions",
        "literature_status",
        "novelty_claim",
        "failure_state",
        "verification",
        "provenance",
        "record",
    }
    if not isinstance(payload, Mapping):
        raise TypeError("snapshot result must be an object")
    if not all(isinstance(key, str) for key in payload):
        raise TypeError("snapshot result keys must be strings")
    unknown = set(payload) - envelope
    if unknown:
        raise ValueError(f"snapshot result contains unexpected keys: {sorted(unknown)}")
    missing = envelope - payload.keys()
    if missing:
        raise ValueError(f"snapshot result is missing keys: {sorted(missing)}")
    if isinstance(payload["schema_version"], bool) or not isinstance(
        payload["schema_version"], int
    ):
        raise TypeError("snapshot result schema_version must be an integer")
    if payload["schema_version"] != SNAPSHOT_SCHEMA_VERSION:
        raise ValueError("unsupported snapshot result schema_version")
    if not isinstance(payload["result_type"], str):
        raise TypeError("snapshot result result_type must be a string")
    if payload["result_type"] not in _SNAPSHOT_RESULT_TYPES:
        raise ValueError(f"unsupported snapshot result_type: {payload['result_type']!r}")
    for key in (
        "method",
        "evidence_status",
        "computational_status",
        "package_version",
        "provenance",
    ):
        if not isinstance(payload[key], str) or not payload[key]:
            raise TypeError(f"snapshot result {key} must be a non-empty string")
    if payload["computational_status"] != payload["evidence_status"]:
        raise ValueError("snapshot result computational_status must match evidence_status")
    for key in ("assumptions", "source_references"):
        if not isinstance(payload[key], list) or not all(
            isinstance(item, str) and item for item in payload[key]
        ):
            raise ValueError(f"snapshot result {key} must be a list of non-empty strings")
    if not isinstance(payload["artifact_versions"], Mapping) or not all(
        isinstance(key, str) and isinstance(value, str) and value
        for key, value in payload["artifact_versions"].items()
    ):
        raise ValueError("snapshot result artifact_versions must map strings to strings")
    required_versions = {"generator_catalog", "source_commit", "fixture_or_proof"}
    if set(payload["artifact_versions"]) < required_versions:
        raise ValueError("snapshot result artifact_versions are incomplete")
    if payload["literature_status"] != LiteratureStatus.NOT_ASSESSED.value:
        raise ValueError("snapshot result literature_status must be not_assessed")
    if payload["novelty_claim"] is not False:
        raise ValueError("snapshot result novelty_claim must be false")
    if payload["failure_state"] is not None:
        raise ValueError("snapshot result failure_state must be null for success")
    verification = payload["verification"]
    if not isinstance(verification, Mapping):
        raise TypeError("snapshot result verification must be an object")
    if verification.get("success") is not True or verification.get("status") != "passed":
        raise ValueError("snapshot result verification must report success")
    checks = verification.get("checks")
    if not isinstance(checks, list) or not checks:
        raise ValueError("snapshot result verification must contain checks")
    if not isinstance(payload["record"], Mapping):
        raise TypeError("snapshot result record must be an object")
    json.dumps(payload, allow_nan=False)
